"""P08-specific, fail-closed experiment evidence utilities."""

from .metrics import (
    DEFAULT_E1_CLASSES,
    DEFAULT_E1_RATES_HZ,
    DEFAULT_E1_SEEDS,
    E1Predictions,
    aggregate_probabilities_by_group,
    balanced_accuracy,
    bootstrap_e1_paired_contrast,
    e1_prediction_consistency,
    e1_representation_distance,
    e1_worst_rate_balanced_accuracy,
    jensen_shannon_divergence,
    record_classification_metrics,
)
from .runtime import (
    ALLOWED_PHYSICAL_GPU_INDICES,
    FORBIDDEN_PHYSICAL_GPU_INDICES,
    DevicePreflightRecord,
    EvidenceWriter,
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    canonical_json_bytes,
    sha256_bytes,
    sha256_file,
    strict_single_gpu_preflight,
)

__all__ = [
    "ALLOWED_PHYSICAL_GPU_INDICES",
    "DEFAULT_E1_CLASSES",
    "DEFAULT_E1_RATES_HZ",
    "DEFAULT_E1_SEEDS",
    "FORBIDDEN_PHYSICAL_GPU_INDICES",
    "DevicePreflightRecord",
    "E1Predictions",
    "EvidenceWriter",
    "aggregate_probabilities_by_group",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "balanced_accuracy",
    "bootstrap_e1_paired_contrast",
    "canonical_json_bytes",
    "e1_prediction_consistency",
    "e1_representation_distance",
    "e1_worst_rate_balanced_accuracy",
    "jensen_shannon_divergence",
    "record_classification_metrics",
    "sha256_bytes",
    "sha256_file",
    "strict_single_gpu_preflight",
]
