"""Maintained explainability and measurement-contract APIs."""

from .eligibility import ExplainEligibility, ExplainReadyResult, explain_ready
from .measurement import (
    MEASUREMENT_SCHEMA_VERSION,
    AdapterIdentity,
    ArrayMeasurementAdapter,
    ArtifactRef,
    MeasurementContractError,
    MeasurementObject,
    SourceIdentity,
    array_sha256,
    assert_measurements_aligned,
    canonical_sha256,
)
from .measurement_metrics import (
    METRIC_REGISTRY,
    METRIC_OBSERVATION_SCHEMA_VERSION,
    MetricObservation,
    MetricInputError,
    activation_ratio,
    aopc,
    assert_metric_compatible,
    deletion_at_fraction,
    deletion_score_curve,
    kendall_tau_b,
    metric_registry_manifest,
    metric_registry_sha256,
    pairwise_rank_reversal_rate,
    peak_memory_mib,
    spearman_attribution,
    topk_iou,
    elapsed_time_ms,
)

__all__ = [
    "MEASUREMENT_SCHEMA_VERSION",
    "METRIC_REGISTRY",
    "METRIC_OBSERVATION_SCHEMA_VERSION",
    "AdapterIdentity",
    "ArrayMeasurementAdapter",
    "ArtifactRef",
    "ExplainEligibility",
    "ExplainReadyResult",
    "MeasurementContractError",
    "MeasurementObject",
    "MetricInputError",
    "MetricObservation",
    "SourceIdentity",
    "aopc",
    "activation_ratio",
    "assert_metric_compatible",
    "array_sha256",
    "assert_measurements_aligned",
    "canonical_sha256",
    "deletion_at_fraction",
    "deletion_score_curve",
    "explain_ready",
    "elapsed_time_ms",
    "kendall_tau_b",
    "metric_registry_manifest",
    "metric_registry_sha256",
    "pairwise_rank_reversal_rate",
    "peak_memory_mib",
    "spearman_attribution",
    "topk_iou",
]
