from __future__ import annotations

import hashlib
import json
import os
import platform
import subprocess
import tempfile
from pathlib import Path
from typing import Any

import torch


def sha256_bytes(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def sha256_file(path: str | Path) -> str:
    candidate = Path(path)
    if not candidate.is_file():
        raise FileNotFoundError(f"evidence file does not exist: {candidate}")
    digest = hashlib.sha256()
    with candidate.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def sha256_json(value: Any) -> str:
    return sha256_bytes(canonical_json_bytes(value))


def atomic_write_json(path: str | Path, value: Any) -> Path:
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(value, indent=2, ensure_ascii=False) + "\n"
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{target.name}.",
        suffix=".tmp",
        dir=str(target.parent),
        text=True,
    )
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_name, target)
    except Exception:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise
    return target


def write_hashed_json(path: str | Path, value: Any) -> tuple[Path, str, Path]:
    target = atomic_write_json(path, value)
    digest = sha256_file(target)
    digest_path = target.with_suffix(target.suffix + ".sha256")
    digest_path.write_text(f"{digest}  {target.name}\n", encoding="utf-8")
    return target, digest, digest_path


def load_hashed_json(
    path: str | Path,
    *,
    expected_hash: str | None = None,
) -> tuple[dict[str, Any], str]:
    target = Path(path)
    digest = sha256_file(target)
    if expected_hash and digest != str(expected_hash):
        raise ValueError(
            f"evidence hash mismatch for {target}: expected {expected_hash}, got {digest}"
        )
    value = json.loads(target.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"evidence JSON must be an object: {target}")
    return value, digest


def git_commit_sha(repository_root: str | Path = ".") -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repository_root),
            text=True,
            capture_output=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return "unavailable"
    return result.stdout.strip() if result.returncode == 0 else "unavailable"


def dependency_lock_evidence(
    candidates: tuple[str, ...] = (
        "requirements.txt",
        "environment.yml",
        "pyproject.toml",
    ),
) -> dict[str, str]:
    for candidate in candidates:
        path = Path(candidate)
        if path.is_file():
            return {"path": candidate, "sha256": sha256_file(path)}
    return {"path": "unavailable", "sha256": "unavailable"}


def runtime_environment() -> dict[str, Any]:
    return {
        "python": platform.python_version(),
        "platform": platform.platform(),
        "torch": torch.__version__,
        "cuda_available": bool(torch.cuda.is_available()),
        "cuda_version": torch.version.cuda,
        "device_count": int(torch.cuda.device_count()),
        "devices": [
            torch.cuda.get_device_name(index)
            for index in range(torch.cuda.device_count())
        ],
    }


def strict_load_lightning_checkpoint(
    module: torch.nn.Module,
    checkpoint_path: str | Path,
    *,
    map_location: str | torch.device = "cpu",
) -> dict[str, Any]:
    """Load a trusted, locally produced checkpoint with strict key matching.

    Pipeline 06 checkpoints are generated by the same repository workflow. The
    explicit ``weights_only=False`` keeps Lightning checkpoint dictionaries
    readable under PyTorch 2.6; callers must not use this function for
    untrusted third-party checkpoint files.
    """

    path = Path(checkpoint_path)
    if not path.is_file():
        raise FileNotFoundError(f"checkpoint does not exist: {path}")
    payload = torch.load(
        path,
        map_location=map_location,
        weights_only=False,
    )
    state_dict = payload.get("state_dict") if isinstance(payload, dict) else None
    if state_dict is None:
        state_dict = payload
    if not isinstance(state_dict, dict):
        raise ValueError(f"checkpoint state_dict is not a mapping: {path}")
    module.load_state_dict(state_dict, strict=True)
    return {
        "path": str(path),
        "sha256": sha256_file(path),
        "state_dict_keys": len(state_dict),
        "strict": True,
    }


def update_stage_ledger(
    path: str | Path,
    *,
    stage: str,
    values: dict[str, Any],
) -> dict[str, Any]:
    if stage not in {"train", "sample", "eval"}:
        raise ValueError(f"unsupported stage ledger entry: {stage}")
    target = Path(path)
    if target.exists():
        ledger, _ = load_hashed_json(target)
    else:
        ledger = {"schema_version": "0.2.1", "stages": {}}
    if not isinstance(ledger.get("stages"), dict):
        raise ValueError(f"invalid stage ledger: {target}")
    stage_values = (
        {}
        if values.get("status") == "running"
        else dict(ledger["stages"].get(stage, {}))
    )
    stage_values.update(values)
    ledger["stages"][stage] = stage_values
    _, ledger_hash, digest_path = write_hashed_json(target, ledger)
    ledger["ledger_sha256"] = ledger_hash
    ledger["ledger_sha256_path"] = str(digest_path)
    return ledger
