"""Clean-room, time-order-only subset of the ICLR 2025 PPT objective."""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F


@dataclass(frozen=True)
class PPTTimeOrderConfig:
    num_patches: int
    embedding_dim: int
    weak_swaps: int = 1
    strong_swaps: int = 5
    bank_size: int = 256
    seed: int = 42
    temperature: float = 0.1
    consistency_weight: float = 1.0
    contrastive_weight: float = 1.0


class PatchPermutationBank(nn.Module):
    """Deterministic bank of patch indices generated by repeated random swaps."""

    def __init__(self, num_patches: int, swaps: int, bank_size: int, seed: int):
        super().__init__()
        if num_patches < 2:
            raise ValueError("PPT permutation requires at least two patches")
        if swaps <= 0:
            raise ValueError("PPT swap frequency must be positive")
        if bank_size <= 0:
            raise ValueError("PPT permutation bank_size must be positive")

        generator = torch.Generator(device="cpu")
        generator.manual_seed(int(seed))
        identity = torch.arange(num_patches, dtype=torch.long)
        rows = []
        for _ in range(bank_size):
            permutation = identity.clone()
            for _ in range(swaps):
                pair = torch.randperm(num_patches, generator=generator)[:2]
                left, right = int(pair[0]), int(pair[1])
                saved = permutation[left].clone()
                permutation[left] = permutation[right]
                permutation[right] = saved
            if torch.equal(permutation, identity):
                permutation[0], permutation[1] = permutation[1].clone(), permutation[0].clone()
            rows.append(permutation)
        self.register_buffer("indices", torch.stack(rows), persistent=True)

    def select(self, batch_size: int, offset: int = 0) -> torch.Tensor:
        rows = (torch.arange(batch_size, device=self.indices.device) + int(offset))
        rows = rows.remainder(self.indices.shape[0])
        return self.indices.index_select(0, rows)

    def permute(self, sequence: torch.Tensor, offset: int = 0) -> torch.Tensor:
        if sequence.ndim != 3:
            raise ValueError("PPT expects patch embeddings shaped [batch, patches, embedding_dim]")
        if sequence.shape[1] != self.indices.shape[1]:
            raise ValueError(
                f"PPT bank contains {self.indices.shape[1]} patches, got {sequence.shape[1]}"
            )
        selected = self.select(sequence.shape[0], offset).unsqueeze(-1)
        selected = selected.expand(-1, -1, sequence.shape[2])
        return sequence.gather(1, selected)


class PPTTimeOrderLoss(nn.Module):
    """Time consistency BCE plus original/weak/strong contrastive loss.

    This component intentionally omits PPT's channel-order losses. For a
    univariate sequence the paper removes those channel terms; the single strong
    sequence is therefore the negative in the time-order InfoNCE denominator.
    """

    def __init__(self, config: PPTTimeOrderConfig):
        super().__init__()
        if config.embedding_dim <= 0:
            raise ValueError("PPT embedding_dim must be positive")
        if config.weak_swaps >= config.strong_swaps:
            raise ValueError("PPT strong_swaps must be greater than weak_swaps")
        if config.temperature <= 0.0:
            raise ValueError("PPT temperature must be positive")
        if config.consistency_weight < 0.0 or config.contrastive_weight < 0.0:
            raise ValueError("PPT loss weights must be non-negative")
        if config.consistency_weight == 0.0 and config.contrastive_weight == 0.0:
            raise ValueError("at least one PPT loss weight must be positive")

        self.config = config
        self.weak_bank = PatchPermutationBank(
            config.num_patches,
            config.weak_swaps,
            config.bank_size,
            config.seed,
        )
        self.strong_bank = PatchPermutationBank(
            config.num_patches,
            config.strong_swaps,
            config.bank_size,
            config.seed + 1,
        )
        self.order_encoder = nn.LSTM(
            input_size=config.embedding_dim,
            hidden_size=config.embedding_dim,
            num_layers=1,
            batch_first=True,
            bidirectional=False,
        )
        self.consistency_head = nn.Linear(config.embedding_dim, 1)

    def _context(self, sequence: torch.Tensor) -> torch.Tensor:
        _, (_, final_cell) = self.order_encoder(sequence)
        return final_cell[-1]

    def forward(self, sequence: torch.Tensor, offset: int = 0):
        if sequence.ndim != 3:
            raise ValueError("PPT expects [batch, patches, embedding_dim]")
        expected = (self.config.num_patches, self.config.embedding_dim)
        if tuple(sequence.shape[1:]) != expected:
            raise ValueError(
                f"PPT expected patch shape {expected}, got {tuple(sequence.shape[1:])}"
            )

        weak = self.weak_bank.permute(sequence, offset)
        strong = self.strong_bank.permute(sequence, offset)
        original_context = self._context(sequence)
        weak_context = self._context(weak)
        strong_context = self._context(strong)

        consistency_logits = torch.cat(
            [
                self.consistency_head(original_context),
                self.consistency_head(strong_context),
            ],
            dim=0,
        ).squeeze(-1)
        consistency_targets = torch.cat(
            [
                torch.ones(sequence.shape[0], device=sequence.device),
                torch.zeros(sequence.shape[0], device=sequence.device),
            ]
        )
        consistency_loss = F.binary_cross_entropy_with_logits(
            consistency_logits,
            consistency_targets,
        )

        positive = F.cosine_similarity(original_context, weak_context, dim=-1)
        negative = F.cosine_similarity(original_context, strong_context, dim=-1)
        contrastive_loss = F.softplus(
            (negative - positive) / self.config.temperature
        ).mean()
        total = (
            self.config.consistency_weight * consistency_loss
            + self.config.contrastive_weight * contrastive_loss
        )
        stats = {
            "loss": total,
            "consistency_loss": consistency_loss,
            "contrastive_loss": contrastive_loss,
            "positive_similarity": positive.mean(),
            "negative_similarity": negative.mean(),
        }
        return total, stats


@dataclass(frozen=True)
class PPTOrderConfig:
    num_patches: int
    num_channels: int
    embedding_dim: int
    order_axes: tuple[str, ...] = ("time", "channel")
    weak_swaps: int = 1
    strong_swaps: int = 5
    channel_weak_swaps: int = 1
    channel_strong_swaps: int = 2
    bank_size: int = 256
    seed: int = 42
    temperature: float = 0.1
    consistency_weight: float = 1.0
    contrastive_weight: float = 1.0
    weighting: str = "fixed"


class PPTOrderLoss(nn.Module):
    """Time- and channel-order PPT objectives over ``[B, C, P, D]`` grids."""

    def __init__(self, config: PPTOrderConfig):
        super().__init__()
        axes = tuple(config.order_axes)
        if not axes or len(set(axes)) != len(axes):
            raise ValueError("PPT order_axes must be a non-empty unique sequence")
        unknown = set(axes) - {"time", "channel"}
        if unknown:
            raise ValueError(f"unsupported PPT order axes: {sorted(unknown)}")
        if config.num_patches < 2:
            raise ValueError("PPT requires at least two patches")
        if config.num_channels <= 0:
            raise ValueError("PPT num_channels must be positive")
        if "channel" in axes and config.num_channels < 3:
            raise ValueError("channel-order PPT requires at least three channels")
        if config.embedding_dim <= 0:
            raise ValueError("PPT embedding_dim must be positive")
        if config.weak_swaps >= config.strong_swaps:
            raise ValueError("PPT strong_swaps must be greater than weak_swaps")
        if "channel" in axes and config.channel_weak_swaps >= config.channel_strong_swaps:
            raise ValueError(
                "PPT channel_strong_swaps must be greater than channel_weak_swaps"
            )
        if config.temperature <= 0.0:
            raise ValueError("PPT temperature must be positive")
        if config.consistency_weight < 0.0 or config.contrastive_weight < 0.0:
            raise ValueError("PPT loss weights must be non-negative")
        if config.consistency_weight == 0.0 and config.contrastive_weight == 0.0:
            raise ValueError("at least one PPT loss weight must be positive")
        if config.weighting not in {"fixed", "uncertainty"}:
            raise ValueError("PPT weighting must be fixed or uncertainty")

        self.config = config
        self.axes = axes
        self.encoders = nn.ModuleDict(
            {
                axis: nn.LSTM(
                    input_size=config.embedding_dim,
                    hidden_size=config.embedding_dim,
                    num_layers=1,
                    batch_first=True,
                    bidirectional=False,
                )
                for axis in axes
            }
        )
        self.consistency_heads = nn.ModuleDict(
            {axis: nn.Linear(config.embedding_dim, 1) for axis in axes}
        )
        self.weak_banks = nn.ModuleDict()
        self.strong_banks = nn.ModuleDict()
        if "time" in axes:
            self.weak_banks["time"] = PatchPermutationBank(
                config.num_patches,
                config.weak_swaps,
                config.bank_size,
                config.seed,
            )
            self.strong_banks["time"] = PatchPermutationBank(
                config.num_patches,
                config.strong_swaps,
                config.bank_size,
                config.seed + 1,
            )
        if "channel" in axes:
            self.weak_banks["channel"] = PatchPermutationBank(
                config.num_channels,
                config.channel_weak_swaps,
                config.bank_size,
                config.seed + 2,
            )
            self.strong_banks["channel"] = PatchPermutationBank(
                config.num_channels,
                config.channel_strong_swaps,
                config.bank_size,
                config.seed + 3,
            )

        self.log_variances = nn.ParameterDict()
        if config.weighting == "uncertainty":
            for axis in axes:
                self.log_variances[f"{axis}_consistency"] = nn.Parameter(torch.zeros(()))
                self.log_variances[f"{axis}_contrastive"] = nn.Parameter(torch.zeros(()))

    def _permute(self, grid: torch.Tensor, axis: str, strong: bool, offset: int):
        bank = self.strong_banks[axis] if strong else self.weak_banks[axis]
        batch_size, channels, patches, embedding_dim = grid.shape
        if axis == "time":
            flattened = grid.reshape(batch_size * channels, patches, embedding_dim)
            return bank.permute(flattened, offset).reshape_as(grid)

        flattened = grid.permute(0, 2, 1, 3).reshape(
            batch_size * patches,
            channels,
            embedding_dim,
        )
        permuted = bank.permute(flattened, offset)
        return permuted.reshape(
            batch_size,
            patches,
            channels,
            embedding_dim,
        ).permute(0, 2, 1, 3)

    def _contexts(self, grid: torch.Tensor, axis: str) -> torch.Tensor:
        batch_size, channels, patches, embedding_dim = grid.shape
        if axis == "time":
            sequences = grid.reshape(batch_size * channels, patches, embedding_dim)
            group_size = channels
        else:
            sequences = grid.permute(0, 2, 1, 3).reshape(
                batch_size * patches,
                channels,
                embedding_dim,
            )
            group_size = patches
        _, (_, final_cell) = self.encoders[axis](sequences)
        return final_cell[-1].reshape(batch_size, group_size, embedding_dim)

    def _axis_losses(
        self,
        original: torch.Tensor,
        weak: torch.Tensor,
        strong: torch.Tensor,
        axis: str,
    ) -> tuple[torch.Tensor, torch.Tensor, dict[str, torch.Tensor]]:
        original_context = self._contexts(original, axis)
        weak_context = self._contexts(weak, axis)
        strong_context = self._contexts(strong, axis)

        consistency_logits = torch.cat(
            [
                self.consistency_heads[axis](original_context).reshape(-1),
                self.consistency_heads[axis](strong_context).reshape(-1),
            ]
        )
        consistency_targets = torch.cat(
            [
                torch.ones(
                    original_context.numel() // original_context.shape[-1],
                    device=original.device,
                ),
                torch.zeros(
                    strong_context.numel() // strong_context.shape[-1],
                    device=original.device,
                ),
            ]
        )
        consistency = F.binary_cross_entropy_with_logits(
            consistency_logits,
            consistency_targets,
        )

        anchors = F.normalize(original_context, dim=-1)
        positives = F.cosine_similarity(anchors, F.normalize(weak_context, dim=-1), dim=-1)
        negatives = torch.einsum(
            "bnd,bmd->bnm",
            anchors,
            F.normalize(strong_context, dim=-1),
        )
        logits = torch.cat([positives.unsqueeze(-1), negatives], dim=-1)
        logits = logits.reshape(-1, logits.shape[-1]) / self.config.temperature
        targets = torch.zeros(logits.shape[0], dtype=torch.long, device=logits.device)
        contrastive = F.cross_entropy(logits, targets)
        stats = {
            f"{axis}_positive_similarity": positives.mean(),
            f"{axis}_negative_similarity": negatives.mean(),
        }
        return consistency, contrastive, stats

    def _weighted(self, name: str, loss: torch.Tensor, fixed_weight: float) -> torch.Tensor:
        if self.config.weighting == "fixed":
            return fixed_weight * loss
        log_variance = self.log_variances[name]
        return torch.exp(-log_variance) * loss + log_variance

    def forward(self, grid: torch.Tensor, offset: int = 0):
        if grid.ndim != 4:
            raise ValueError("PPTOrderLoss expects [batch, channels, patches, embedding_dim]")
        expected = (
            self.config.num_channels,
            self.config.num_patches,
            self.config.embedding_dim,
        )
        if tuple(grid.shape[1:]) != expected:
            raise ValueError(f"PPT expected grid shape {expected}, got {tuple(grid.shape[1:])}")

        total = grid.sum() * 0.0
        stats: dict[str, torch.Tensor] = {}
        for axis_index, axis in enumerate(self.axes):
            axis_offset = int(offset) + axis_index * 104_729
            weak = self._permute(grid, axis, strong=False, offset=axis_offset)
            strong = self._permute(grid, axis, strong=True, offset=axis_offset)
            consistency, contrastive, axis_stats = self._axis_losses(
                grid,
                weak,
                strong,
                axis,
            )
            total = total + self._weighted(
                f"{axis}_consistency",
                consistency,
                self.config.consistency_weight,
            )
            total = total + self._weighted(
                f"{axis}_contrastive",
                contrastive,
                self.config.contrastive_weight,
            )
            stats[f"{axis}_consistency_loss"] = consistency
            stats[f"{axis}_contrastive_loss"] = contrastive
            stats.update(axis_stats)

        stats["loss"] = total
        return total, stats
