# Multi-Task PHM Foundation Model Configuration - B_04_Dlinear
# Test Mode: 1 epoch, wandb dryrun, swanlab off
# Author: PHM-Vibench Team
# Date: 2025-08-29

environment:
  VBENCH_HOME: "/home/lq/LQcode/2_project/PHMBench/Vbench"
  PYTHONPATH: "/home/lq/.conda/envs/lq"
  PHMBench: "/home/lq/LQcode/2_project/PHMBench"
  project: "MultiTask_Foundation_Model"
  seed: 42
  output_dir: "results/multitask_B_04_Dlinear"
  iterations: 1  # Test mode: single iteration
  wandb: dryrun  # Test mode: dryrun (no upload)
  swanlab: False  # Test mode: disabled
  notes: 'Multi-task foundation model with B_04_Dlinear - TEST MODE'
  workspace: 'PHMbench'

# Data Configuration
data:
  data_dir: "./data/"
  metadata_file: "metadata_6_11.xlsx"
  batch_size: 128
  num_workers: 32
  window_size: 4096
  stride: 4
  truncate_length: 200
  num_window: 4 #
  normalization: 'standardization'
  dtype: float32
  window_sampling_strategy: 'evenly_spaced'
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  
  # RUL-specific dataset configuration
  rul_dataset_id: 2  # XJTU bearing dataset for RUL

# Model Configuration
model:
  name: "M_01_ISFM"
  type: "ISFM"
  input_dim: 2
  
  # Architecture components
  embedding: E_01_HSE
  backbone: B_04_Dlinear  # Dlinear backbone
  task_head: MultiTaskHead  # Enhanced multi-task head with signal prediction
  
  # Model dimensions
  num_patches: 128
  patch_size_L: 256
  patch_size_C: 1
  output_dim: 1024
  num_heads: 8
  num_layers: 3
  d_ff: 2048
  dropout: 0.1
  
  # Multi-task head configuration
  classification_head: H_02_distance_cla
  prediction_head: H_03_Linear_pred
  hidden_dim: 512
  activation: "gelu"
  rul_max_value: 2000.0
  use_batch_norm: true
  
  # H_03_Linear_pred parameters for signal prediction
  max_len: 4096
  max_out: 3
  act: "gelu"

# Task Configuration
task:
  name: "multi_task_phm"
  type: "In_distribution"
  
  # Enabled tasks
  enabled_tasks: 
    - 'classification'       # Fault diagnosis
    - 'anomaly_detection'   # Anomaly detection  
    - 'signal_prediction'   # Signal prediction
    - 'rul_prediction'      # RUL prediction
  
  # Task weights for loss balancing
  task_weights:
    classification: 1.0
    anomaly_detection: 0.6
    signal_prediction: 0.7
    rul_prediction: 0.8
  
  # Task-specific configurations
  classification:
    loss: "CE"  # Cross-entropy loss
    num_classes: auto  # Auto-determined from dataset
    label_smoothing: 0.1
    loss_weight: 1.0
  
  anomaly_detection:
    loss: "BCE"  # Binary cross-entropy loss
    threshold: 0.5
    class_weights: [1.0, 2.0]  # [normal, anomaly]
    loss_weight: 0.6
  
  signal_prediction:
    loss: "MSE"  # Mean squared error loss
    pred_len: 96  # Predict 96 timesteps
    use_mean_pooling: false  # Key: don't use mean pooling
    loss_weight: 0.7
  
  rul_prediction:
    loss: "MSE"  # Mean squared error loss
    max_rul_value: 2000.0
    normalize_targets: true
    dataset_id: 2  # XJTU dataset
    loss_weight: 0.8
  
  # Target systems for evaluation
  # target_system_id: [1, 2, 5, 6, 13, 19]
  target_system_id: [2]  # Test mode: single system
  
  # Optimization parameters
  optimizer: "adamw"
  lr: 0.0005
  weight_decay: 0.01
  momentum: 0.9  # For SGD if needed
  
  # Learning rate scheduling
  scheduler:
    name: "cosine"
    options:
      T_max: 100
      eta_min: 1e-6

# Trainer Configuration
trainer:
  name: "Default_trainer"
  num_epochs: 1  # Test mode: 1 epoch only
  gpus: 1
  precision: 16  # Mixed precision
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
  
  # Early stopping (disabled for test mode)
  early_stopping: false  # Test mode: disabled
  patience: 25
  monitor: "val_loss"
  
  # Model checkpointing
  save_top_k: 3
  save_last: true
  
  # Logging
  log_every_n_steps: 50
  
  # Device configuration
  device: 'cuda'
  
  # Validation
  val_check_interval: 1.0
  check_val_every_n_epoch: 1

# Evaluation Configuration
evaluation:
  # Metrics to compute during evaluation
  compute_metrics:
    - "accuracy"      # For classification
    - "f1_score"      # For classification & anomaly detection
    - "precision"     # For classification & anomaly detection  
    - "recall"        # For classification & anomaly detection
    - "roc_auc"       # For anomaly detection
    - "mse"           # For RUL & signal prediction
    - "mae"           # For RUL & signal prediction
    - "r2_score"      # For RUL & signal prediction
  
  # Test after training
  test_after_training: true

# Reproducibility
reproducibility:
  deterministic: true
  benchmark: false
  seed_everything: true

# Advanced Configuration (Test Mode)
advanced:
  effective_batch_size: 256  # Smaller for testing
  use_amp: true  # Mixed precision
  compile_model: false
  memory_efficient: true
  profiler: null  # No profiling in test mode