"""Shared Streamlit session-state keys."""

SELECTED_CONFIG_KEY = "phmfactory_selected_config"
LAST_LAUNCH_KEY = "phmfactory_last_launch"
LAST_PREFLIGHT_KEY = "phmfactory_last_preflight"
SELECTED_RUN_KEY = "phmfactory_selected_run"
RUN_FILTER_QUERY_KEY = "phmfactory_run_filter_query"
RUN_FILTER_EVIDENCE_KEY = "phmfactory_run_filter_evidence"
COMPARE_BASELINE_RUN_KEY = "phmfactory_compare_baseline_run"
COMPARE_SELECTED_RUNS_KEY = "phmfactory_compare_selected_runs"
COMPOSE_NOTES_KEY = "phmfactory_compose_notes"
COMPOSE_OVERRIDE_TEXT_KEY = "phmfactory_compose_override_text"
COMPOSE_INPUT_FINGERPRINT_KEY = "phmfactory_compose_input_fingerprint"
COMPOSE_PREFLIGHT_RESULT_KEY = "phmfactory_compose_preflight_result"
COMPOSE_PREFLIGHT_ERROR_KEY = "phmfactory_compose_preflight_error"
